import { AppState } from '../types';

export const seedData: AppState = {
  pillars: [
    {
      id: 'pillar-1',
      name: 'Financial',
      description: 'Financial health and growth objectives',
      displayOrder: 1,
      ragStatus: 'green',
    },
    {
      id: 'pillar-2',
      name: 'Customer',
      description: 'Customer satisfaction and loyalty metrics',
      displayOrder: 2,
      ragStatus: 'amber',
    },
    {
      id: 'pillar-3',
      name: 'Internal Processes',
      description: 'Operational excellence and efficiency',
      displayOrder: 3,
      ragStatus: 'green',
    },
    {
      id: 'pillar-4',
      name: 'Learning & Growth',
      description: 'Employee development and organizational capability',
      displayOrder: 4,
      ragStatus: 'red',
    },
  ],
  kpis: [
    {
      id: 'kpi-1',
      pillarId: 'pillar-1',
      name: 'Revenue Growth YoY',
      targetValue: 12,
      currentValue: 15,
      previousValue: 10,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-2',
      pillarId: 'pillar-1',
      name: 'Cost Reduction',
      targetValue: 100,
      currentValue: 98,
      previousValue: 95,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-3',
      pillarId: 'pillar-2',
      name: 'NPS Score',
      targetValue: 50,
      currentValue: 42,
      previousValue: 45,
      unit: 'score',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-4',
      pillarId: 'pillar-2',
      name: 'Customer Churn Rate',
      targetValue: 3,
      currentValue: 5.1,
      previousValue: 4.2,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-5',
      pillarId: 'pillar-3',
      name: 'Operational Efficiency',
      targetValue: 90,
      currentValue: 92,
      previousValue: 88,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-6',
      pillarId: 'pillar-3',
      name: 'Process Automation Rate',
      targetValue: 75,
      currentValue: 78,
      previousValue: 70,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-7',
      pillarId: 'pillar-4',
      name: 'Key Role Retention',
      targetValue: 95,
      currentValue: 85,
      previousValue: 90,
      unit: '%',
      lastUpdated: '2024-12-01',
    },
    {
      id: 'kpi-8',
      pillarId: 'pillar-4',
      name: 'Training Hours per Employee',
      targetValue: 40,
      currentValue: 32,
      previousValue: 28,
      unit: 'number',
      lastUpdated: '2024-12-01',
    },
  ],
  initiatives: [
    {
      id: 'init-1',
      pillarId: 'pillar-2',
      name: 'Global CRM Rollout',
      description: 'Implement new CRM system across all regions',
      ownerId: 'res-1',
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      budget: 1500000,
      spentBudget: 1100000,
      ragStatus: 'amber',
    },
    {
      id: 'init-2',
      pillarId: 'pillar-3',
      name: 'Supply Chain Automation',
      description: 'Automate supply chain processes for efficiency',
      ownerId: 'res-2',
      startDate: '2024-03-01',
      endDate: '2025-06-30',
      budget: 3200000,
      spentBudget: 1800000,
      ragStatus: 'green',
    },
    {
      id: 'init-3',
      pillarId: 'pillar-1',
      name: 'Data-Driven Revenue',
      description: 'Leverage data analytics for revenue optimization',
      ownerId: 'res-3',
      startDate: '2024-02-01',
      endDate: '2024-11-30',
      budget: 800000,
      spentBudget: 650000,
      ragStatus: 'green',
    },
    {
      id: 'init-4',
      pillarId: 'pillar-4',
      name: 'Key Role Retention Program',
      description: 'Programs to improve retention of critical talent',
      ownerId: 'res-4',
      startDate: '2024-04-01',
      endDate: '2024-12-31',
      budget: 500000,
      spentBudget: 420000,
      ragStatus: 'red',
    },
    {
      id: 'init-5',
      pillarId: 'pillar-2',
      name: 'Customer Retention Drive',
      description: 'Initiatives to reduce churn and improve loyalty',
      ownerId: 'res-1',
      startDate: '2024-05-01',
      endDate: '2025-03-31',
      budget: 950000,
      spentBudget: 380000,
      ragStatus: 'amber',
    },
    {
      id: 'init-6',
      pillarId: 'pillar-3',
      name: 'Operational Efficiency',
      description: 'Streamline operations across departments',
      ownerId: 'res-5',
      startDate: '2024-01-15',
      endDate: '2024-10-31',
      budget: 600000,
      spentBudget: 520000,
      ragStatus: 'green',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      initiativeId: 'init-1',
      name: 'CRM Vendor Selection',
      description: 'Evaluate and select CRM vendor',
      managerId: 'res-1',
      status: 'completed',
      ragStatus: 'green',
      startDate: '2024-01-01',
      endDate: '2024-03-31',
      completionPercentage: 100,
      budget: 100000,
      spentBudget: 95000,
    },
    {
      id: 'proj-2',
      initiativeId: 'init-1',
      name: 'Project Phoenix - Data Migration',
      description: 'Migrate customer data to new CRM',
      managerId: 'res-6',
      status: 'in_progress',
      ragStatus: 'amber',
      startDate: '2024-04-01',
      endDate: '2024-09-30',
      completionPercentage: 65,
      budget: 600000,
      spentBudget: 480000,
    },
    {
      id: 'proj-3',
      initiativeId: 'init-1',
      name: 'CRM Training Program',
      description: 'Train staff on new CRM system',
      managerId: 'res-4',
      status: 'in_progress',
      ragStatus: 'red',
      startDate: '2024-07-01',
      endDate: '2024-11-30',
      completionPercentage: 30,
      budget: 200000,
      spentBudget: 180000,
    },
    {
      id: 'proj-4',
      initiativeId: 'init-2',
      name: 'Warehouse Automation',
      description: 'Automate warehouse operations',
      managerId: 'res-2',
      status: 'in_progress',
      ragStatus: 'green',
      startDate: '2024-03-01',
      endDate: '2024-12-31',
      completionPercentage: 75,
      budget: 1500000,
      spentBudget: 1100000,
    },
    {
      id: 'proj-5',
      initiativeId: 'init-2',
      name: 'Logistics Optimization',
      description: 'Optimize logistics and delivery routes',
      managerId: 'res-7',
      status: 'in_progress',
      ragStatus: 'green',
      startDate: '2024-06-01',
      endDate: '2025-03-31',
      completionPercentage: 45,
      budget: 800000,
      spentBudget: 350000,
    },
    {
      id: 'proj-6',
      initiativeId: 'init-3',
      name: 'Analytics Platform',
      description: 'Build data analytics platform',
      managerId: 'res-3',
      status: 'in_progress',
      ragStatus: 'green',
      startDate: '2024-02-01',
      endDate: '2024-08-31',
      completionPercentage: 90,
      budget: 450000,
      spentBudget: 420000,
    },
    {
      id: 'proj-7',
      initiativeId: 'init-4',
      name: 'Project Beta - Talent Assessment',
      description: 'Assess critical talent retention risks',
      managerId: 'res-4',
      status: 'in_progress',
      ragStatus: 'red',
      startDate: '2024-04-01',
      endDate: '2024-09-30',
      completionPercentage: 50,
      budget: 150000,
      spentBudget: 140000,
    },
    {
      id: 'proj-8',
      initiativeId: 'init-5',
      name: 'Customer Feedback System',
      description: 'Implement customer feedback collection',
      managerId: 'res-8',
      status: 'in_progress',
      ragStatus: 'amber',
      startDate: '2024-05-01',
      endDate: '2024-12-31',
      completionPercentage: 55,
      budget: 300000,
      spentBudget: 180000,
    },
  ],
  tasks: [
    // Project Phoenix tasks
    {
      id: 'task-1',
      projectId: 'proj-2',
      title: 'Define Data Schema',
      description: 'Define the data schema for migration',
      assigneeId: 'res-9',
      kanbanStatus: 'done',
      dueDate: '2024-04-15',
      estimatedHours: 40,
      actualHours: 38,
    },
    {
      id: 'task-2',
      projectId: 'proj-2',
      title: 'Migrate EU Customer Data',
      description: 'Migrate customer data from EU region',
      assigneeId: 'res-9',
      kanbanStatus: 'in_progress',
      dueDate: '2024-05-20',
      estimatedHours: 120,
      actualHours: 80,
    },
    {
      id: 'task-3',
      projectId: 'proj-2',
      title: 'Data Migration Scripts',
      description: 'Write data migration automation scripts',
      assigneeId: 'res-10',
      kanbanStatus: 'in_progress',
      dueDate: '2024-06-01',
      estimatedHours: 80,
      actualHours: 45,
    },
    {
      id: 'task-4',
      projectId: 'proj-2',
      title: 'QA Testing - Phase 1',
      description: 'Quality assurance testing for first migration phase',
      assigneeId: 'res-8',
      kanbanStatus: 'todo',
      dueDate: '2024-06-15',
      estimatedHours: 60,
      actualHours: 0,
    },
    {
      id: 'task-5',
      projectId: 'proj-2',
      title: 'Define CRM Requirements',
      description: 'Document CRM system requirements',
      assigneeId: 'res-1',
      kanbanStatus: 'done',
      dueDate: '2024-04-30',
      estimatedHours: 24,
      actualHours: 28,
    },
    {
      id: 'task-6',
      projectId: 'proj-2',
      title: 'Velocity Requirements',
      description: 'Define performance requirements',
      assigneeId: 'res-6',
      kanbanStatus: 'in_progress',
      dueDate: '2024-05-25',
      estimatedHours: 16,
      actualHours: 12,
    },
    {
      id: 'task-7',
      projectId: 'proj-2',
      title: 'User Training Modules',
      description: 'Create training modules for end users',
      assigneeId: 'res-4',
      kanbanStatus: 'blocked',
      dueDate: '2024-06-30',
      estimatedHours: 40,
      actualHours: 8,
    },
    {
      id: 'task-8',
      projectId: 'proj-2',
      title: 'Define Migration Exceptions',
      description: 'Handle edge cases in data migration',
      assigneeId: 'res-10',
      kanbanStatus: 'blocked',
      dueDate: '2024-06-10',
      estimatedHours: 32,
      actualHours: 16,
    },
    // Training tasks
    {
      id: 'task-9',
      projectId: 'proj-3',
      title: 'Create Training Materials',
      description: 'Develop CRM training documentation',
      assigneeId: 'res-4',
      kanbanStatus: 'in_progress',
      dueDate: '2024-08-15',
      estimatedHours: 60,
      actualHours: 25,
    },
    {
      id: 'task-10',
      projectId: 'proj-3',
      title: 'Schedule Training Sessions',
      description: 'Coordinate training schedule across teams',
      assigneeId: 'res-4',
      kanbanStatus: 'todo',
      dueDate: '2024-09-01',
      estimatedHours: 20,
      actualHours: 0,
    },
    // Warehouse automation tasks
    {
      id: 'task-11',
      projectId: 'proj-4',
      title: 'Install Automation Hardware',
      description: 'Install conveyor and sorting systems',
      assigneeId: 'res-2',
      kanbanStatus: 'done',
      dueDate: '2024-06-30',
      estimatedHours: 200,
      actualHours: 180,
    },
    {
      id: 'task-12',
      projectId: 'proj-4',
      title: 'Integration Testing',
      description: 'Test automation system integration',
      assigneeId: 'res-7',
      kanbanStatus: 'in_progress',
      dueDate: '2024-08-15',
      estimatedHours: 80,
      actualHours: 50,
    },
    // Analytics tasks
    {
      id: 'task-13',
      projectId: 'proj-6',
      title: 'Build Dashboard Framework',
      description: 'Create dashboard visualization framework',
      assigneeId: 'res-3',
      kanbanStatus: 'done',
      dueDate: '2024-05-15',
      estimatedHours: 100,
      actualHours: 95,
    },
    {
      id: 'task-14',
      projectId: 'proj-6',
      title: 'Data Pipeline Setup',
      description: 'Configure data ingestion pipelines',
      assigneeId: 'res-9',
      kanbanStatus: 'done',
      dueDate: '2024-06-01',
      estimatedHours: 80,
      actualHours: 75,
    },
  ],
  resources: [
    {
      id: 'res-1',
      name: 'Jane Doe',
      email: 'jane.doe@company.com',
      role: 'Senior PM',
      team: 'PMO',
      weeklyCapacity: 40,
      avatarColor: '#3b82f6',
    },
    {
      id: 'res-2',
      name: 'Bob Jones',
      email: 'bob.jones@company.com',
      role: 'Operations Director',
      team: 'Operations',
      weeklyCapacity: 40,
      avatarColor: '#22c55e',
    },
    {
      id: 'res-3',
      name: 'Alice Chen',
      email: 'alice.chen@company.com',
      role: 'Data Science Lead',
      team: 'Analytics',
      weeklyCapacity: 40,
      avatarColor: '#8b5cf6',
    },
    {
      id: 'res-4',
      name: 'Mike Brown',
      email: 'mike.brown@company.com',
      role: 'HR Director',
      team: 'Human Resources',
      weeklyCapacity: 40,
      avatarColor: '#f59e0b',
    },
    {
      id: 'res-5',
      name: 'Sarah Lee',
      email: 'sarah.lee@company.com',
      role: 'Process Excellence Lead',
      team: 'Operations',
      weeklyCapacity: 40,
      avatarColor: '#ec4899',
    },
    {
      id: 'res-6',
      name: 'Tom Wilson',
      email: 'tom.wilson@company.com',
      role: 'Technical PM',
      team: 'IT',
      weeklyCapacity: 40,
      avatarColor: '#06b6d4',
    },
    {
      id: 'res-7',
      name: 'Emily Davis',
      email: 'emily.davis@company.com',
      role: 'Logistics Manager',
      team: 'Operations',
      weeklyCapacity: 40,
      avatarColor: '#f43f5e',
    },
    {
      id: 'res-8',
      name: 'James Taylor',
      email: 'james.taylor@company.com',
      role: 'QA Lead',
      team: 'Quality',
      weeklyCapacity: 40,
      avatarColor: '#14b8a6',
    },
    {
      id: 'res-9',
      name: 'John Smith',
      email: 'john.smith@company.com',
      role: 'Cloud Architect',
      team: 'IT Infrastructure',
      weeklyCapacity: 40,
      avatarColor: '#a855f7',
    },
    {
      id: 'res-10',
      name: 'Lisa Wang',
      email: 'lisa.wang@company.com',
      role: 'Senior Developer',
      team: 'Engineering',
      weeklyCapacity: 40,
      avatarColor: '#eab308',
    },
  ],
};
